# The Docker image that will be used to build your app
image: node:lts


cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache
    
# Functions that should be executed before the build script is run
before_script:
  - npm install

build:
  stage: build
  script:
    - npx next build

pages:
  stage: deploy
  script:
    - mv kinact-package/* public
  artifacts:
    paths:
      - public
  only:
    - main