# The Docker image that will be used to build your app
image: node:20

variables:
  NODE_ENV: production
  NEXT_PUBLIC_BASE_PATH: "/"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache
    
# Functions that should be executed before the build script is run
before_script:
  - yarn install

build:
  stage: build
  script:
    - yarn next build --no-lint
  artifacts:
    paths:
      - kinact-package/
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r kinact-package/. .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main