# The Docker image that will be used to build your app
image: node:lts


cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache
    
pages:
  stage: deploy
  before_script:
  - npm install
  - npx next build
  script:
    - mv -f kinact-package/* public
  artifacts:
    paths:
      - public
  only:
    - main